version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: imagedefinitions.json
        LoadBalancerInfo:
          ContainerName: "main"
          ContainerPort: 80